name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - jupyterlab=4.0.0
  - seaborn=0.12.2
  - pandas=1.2.3
  - pip=23.1
  - pandas-profiling=2.9.0
  - pyarrow=11.0.0
  - pip:
      - wandb==0.15.0