name: p2_mlops_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - mlflow=2.2.1
  - ipython=8.12.2
  - notebook=6.5.4
  - jupyterlab=4.0.0
  - cookiecutter=2.1.1
  - hydra-core=1.0.6
  - matplotlib=3.7.1
  - pandas=1.2.3
  - git=2.40.1
  - pip=23.1
  - requests=2.29.0
  - scikit-learn=1.2.2
  - pyyaml=6.0
  - pytest=7.3.1
  - scipy=1.10.1
  - seaborn=0.12.2
  - pandas-profiling=2.9.0
  - pyarrow=11.0.0
  - pillow=9.5.0
  - numpy=1.23.5
  - appdirs=1.4.4
  - protobuf=3.20.3
  - pip:
      - wandb==0.15.0
