name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - pandas=1.2.3
  - pip=23.1
  - mlflow=2.2.1
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - pillow=9.5.0
  - pip:
      - wandb==0.15.0
